name: whats_app
description: An application to create, send and receive messages

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies from pub.dev
  cupertino_icons: ^1.0.0
  flutter_sound: ^7.7.0+1
  logger: ^0.9.4
  path_provider: ^1.6.28

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true